import { CompletionItem, CompletionItemKind } from 'vscode';

export const constantCompletions: CompletionItem[] = [
    new CompletionItem('game["state"]', CompletionItemKind.Constant),
    new CompletionItem('game["teamScores"]', CompletionItemKind.Constant),
    new CompletionItem('game["teamScores"]["allies"]', CompletionItemKind.Constant),
    new CompletionItem('game["teamScores"]["axis"]', CompletionItemKind.Constant),
    new CompletionItem('game["defcon"]', CompletionItemKind.Constant),
    new CompletionItem('game["entity_headicon_allies"]', CompletionItemKind.Constant),
    new CompletionItem('game["entity_headicon_axis"]', CompletionItemKind.Constant),
    new CompletionItem('game["thermal_vision"]', CompletionItemKind.Constant),
    new CompletionItem('game["gamestarted"]', CompletionItemKind.Constant),
    new CompletionItem('game["menu_team"]', CompletionItemKind.Constant),
    new CompletionItem('game["status"]', CompletionItemKind.Constant),
    new CompletionItem('game["icons"]', CompletionItemKind.Constant),
    new CompletionItem('game["icons"]["allies"]', CompletionItemKind.Constant),
    new CompletionItem('game["icons"]["axis"]', CompletionItemKind.Constant),
    new CompletionItem('game["menu_endgameupdate"]', CompletionItemKind.Constant),
    new CompletionItem('game["strings"]', CompletionItemKind.Constant),
    new CompletionItem('game["roundMillisecondsAlreadyPassed"]', CompletionItemKind.Constant),
    new CompletionItem('game["switchedsides"]', CompletionItemKind.Constant),
    new CompletionItem('game["roundsWon"]', CompletionItemKind.Constant),
    new CompletionItem('game["roundsWon"]["allies"]', CompletionItemKind.Constant),
    new CompletionItem('game["roundsWon"]["axis"]', CompletionItemKind.Constant),
    new CompletionItem('game["defenders"]', CompletionItemKind.Constant),
    new CompletionItem('game["roundsPlayed"]', CompletionItemKind.Constant),
    new CompletionItem('game["clientid"]', CompletionItemKind.Constant),
    new CompletionItem('game["allies"]', CompletionItemKind.Constant),
    new CompletionItem('game["axis"]', CompletionItemKind.Constant),
    new CompletionItem('game["attackers"]', CompletionItemKind.Constant),
    new CompletionItem('game["colors"]', CompletionItemKind.Constant),
    new CompletionItem('game["colors"]["blue"]', CompletionItemKind.Constant),
    new CompletionItem('game["colors"]["red"]', CompletionItemKind.Constant),
    new CompletionItem('game["colors"]["white"]', CompletionItemKind.Constant),
    new CompletionItem('game["colors"]["black"]', CompletionItemKind.Constant),
    new CompletionItem('game["colors"]["green"]', CompletionItemKind.Constant),
    new CompletionItem('game["colors"]["yellow"]', CompletionItemKind.Constant),
    new CompletionItem('game["colors"]["orange"]', CompletionItemKind.Constant),
    new CompletionItem('game["colors"]["allies"]', CompletionItemKind.Constant),
    new CompletionItem('game["colors"]["axis"]', CompletionItemKind.Constant),
    new CompletionItem('game["timePassed"]', CompletionItemKind.Constant),
    new CompletionItem('game["clientMatchDataDef"]', CompletionItemKind.Constant),
    new CompletionItem('game["inNukeOvertime"]', CompletionItemKind.Constant)
];
