export var waittills = new Array<string>();

waittills = [
    'player Waittill("menuresponse", menu, response);',
    'player Waittill("spawned_player");',
    'player Waittill("death");',
    'player Waittill("joined_team");',
    'player Waittill("reload");',
    'player Waittill("adjustedStance");',
    'player Waittill("jumped");',
    'player Waittill("weapon_change", weapon);',
    'player Waittill("grenade_fire", grenade, grenadeName);',
    'player Waittill("damage", damage, attacker, direction_vec, point, type, modelName, tagName, partName, iDFlags, weapon);',
    'player Waittill("killed_enemy");',
    'player Waittill("stopRevenge");',
    'player Waittill("disconnect");',
    'self Waittill("menuresponse", menu, response);',
    'self Waittill("spawned_player");',
    'self Waittill("death");',
    'self Waittill("joined_team");',
    'self Waittill("reload");',
    'self Waittill("adjustedStance");',
    'self Waittill("jumped");',
    'self Waittill("weapon_change", weapon);',
    'self Waittill("grenade_fire", grenade, grenadeName);',
    'self Waittill("damage", damage, attacker, direction_vec, point, type, modelName, tagName, partName, iDFlags, weapon);',
    'self Waittill("killed_enemy");',
    'self Waittill("stopRevenge");',
    'self Waittill("disconnect");',
    'level Waittill("putout_fires");',
    'level Waittill("new_destructible_spotlight");',
    'level Waittill("connecting", player);',
    'level Waittill("prematch_over");',
    'level Waittill("createfx_common_done");',
    'level Waittill("connected", player);',
    'level Waittill("eternity");',
    'level Waittill("game_ended");',
    'level Waittill("connected", player);',
    'level Waittill("rain_change", change, blendTime);',
    'level Waittill("disconnected", player);',
    'level Waittill("emp_update");',
    'level Waittill("player_spawned", player);',
    'level Waittill("host_migration_begin");',
    'level Waittill("final_killcam_done");',
    'level Waittill("radar_status_change");',
    'level Waittill("host_migration_end");',
    'level Waittill("restarting");',
    'level Waittill("player_eliminated", player);',
    'level Waittill("hq_captured");',
    'level Waittill("hq_destroyed");',
    'level Waittill("juggernaut_equipped", player);',
    'level Waittill("nuke_death");',
    'level Waittill("new_ent_selection");',
    'level Waittill("new_createfx_centerprint");',
    'level Waittill("set_disable_friendlyfire_value_delayed");',
    'level Waittill("handle_destructible_frame_queue");',
    'level Waittill("stop all gunfireloopfx");',
    'level Waittill("newpath");',
    'level Waittill("end_game");',
    'level Waittill("matchevent_started");',
    'level Waittill("end_draw_map_bounds");',
    'level Waittill("abort_forfeit");',
    'level Waittill("match_forfeit_timer_beginning");',
    'level Waittill("match_start_timer_beginning");',
    'level Waittill("hostmigration_enoughplayers");',
    'level Waittill("stop_spawn_profile");',
    'level Waittill("end_spawn_graph");',
    'level Waittill("spawn_graph_stop_draw");',
    'level Waittill("stop_spawn_weight_debug");',
    'level Waittill("exitLevel_called");',
    'level Waittill("smokeTimesUp");',
    'level Waittill("down_to_one");',
    'level Waittill("arena_flag_time");',
    'level Waittill("reset_grnd_drops");',
    'level Waittill("hq_reset");',
    'level Waittill("awardHQPointsRunning");',
    'level Waittill("bomb_defused");',
    'level Waittill("overtime_ended");',
    'level Waittill("disconnect");',
    'level Waittill("waitSkipped");',
    'level Waittill("graceperiod_done");',
    'level Waittill("ac130player_removed");',
    'level Waittill("post_effects_disabled");',
    'level Waittill("stop_rotatePlane_thread");',
    'level Waittill("gun_fired_and_ready_105mm");',
    'level Waittill("debug_airstrike");',
    'level Waittill("keepEMPTimeRemaining");',
    'level Waittill("emp_ended");',
    'level Waittill("helicopter_done");',
    'level Waittill("nuke_EMPJam");',
    'level Waittill("keepNukeEMPTimeRemaining");',
    'level Waittill("nuke_emp_ended");',
];