// IW5 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

init()
{

}

onplayerconnect()
{
    for (;;)
    {
        level waittill( "connected", var_0 );
        var_0 thread updatereflectionprobe();
    }
}

showspawnpoint( var_0, var_1, var_2 )
{

}

showspawnpoints()
{

}

print3duntilnotified( var_0, var_1, var_2, var_3, var_4 )
{

}

lineuntilnotified( var_0, var_1, var_2, var_3 )
{

}

hidespawnpoints()
{

}

updatereflectionprobe()
{

}

reflectionprobebuttons()
{

}

gotonextspawn()
{

}

gotoprevspawn()
{

}
